package com.edward.physicalcraft;
import android.view.*;import android.graphics.*;import java.util.*;

final class HudView extends View {
 private final MainActivity a;private final Paint p=new Paint(3);private float scale=1,w,h,l,r,t,b;int safeLeft,safeRight,safeTop,safeBottom;
 private final Map<String,RectF> buttons=new LinkedHashMap<>();private int stickId=-1,lookId=-1;private float lx,ly,sx,sy;private String pressed;
 HudView(MainActivity a){super(a);this.a=a;setLayerType(View.LAYER_TYPE_SOFTWARE,null);setContentDescription("PhysicalCraft. Controle de movimento à esquerda, câmera à direita e botão investigar próximo à ruína.");}
 private void txt(Canvas c,String s,float x,float y,float size,int color,boolean bold){p.setColor(color);p.setTextSize(size);p.setTypeface(bold?Typeface.create("sans-serif",Typeface.BOLD):Typeface.create("sans-serif",Typeface.NORMAL));c.drawText(s,x,y,p);}
 private void rect(Canvas c,float x,float y,float width,float height,int color,float rad){p.setColor(color);c.drawRoundRect(x,y,x+width,y+height,rad,rad,p);}
 private void btn(Canvas c,String key,String label,float x,float y,float width,float height,boolean filled){RectF box=new RectF(x,y,x+width,y+height);buttons.put(key,box);rect(c,x,y,width,height,filled?MainActivity.MINT:0xdd142e39,13);p.setTextSize(15);p.setTypeface(Typeface.DEFAULT_BOLD);float tw=p.measureText(label);txt(c,label,x+(width-tw)/2,y+height/2+5,15,filled?MainActivity.BG:MainActivity.TEXT,true);}
 @Override protected void onDraw(Canvas c){super.onDraw(c);scale=getHeight()/520f;w=getWidth()/scale;h=520;l=safeLeft/scale+24;r=w-safeRight/scale-24;t=safeTop/scale+22;b=h-safeBottom/scale-22;c.save();c.scale(scale,scale);buttons.clear();
  if(!a.started){rect(c,0,0,w,h,0x99081822,0);txt(c,"P H Y S I C A L C R A F T",l+18,t+28,16,MainActivity.MINT,true);txt(c,"O universo guarda",l+18,t+118,46,MainActivity.TEXT,true);txt(c,"uma pergunta.",l+18,t+173,46,MainActivity.TEXT,true);txt(c,"Explore. Experimente. Descubra.",l+20,t+223,22,MainActivity.GOLD,false);txt(c,"Uma expedição de física, das forças à luz quântica.",l+20,t+258,16,MainActivity.TEXT,false);btn(c,"start",a.completed>0?"Continuar expedição":"Começar expedição",l+20,b-113,238,54,true);btn(c,"gemma","Configurar Gemma",l+274,b-113,194,54,false);txt(c,"MUNDO LOCAL  /  PROGRESSO SALVO  /  SEM CONTA",l+20,b-29,12,MainActivity.MUTED,true);c.restore();postInvalidateDelayed(80);return;}
  rect(c,l,t,350,112,0xe00c202a,17);txt(c,"PHYSICALCRAFT  /  EXPEDIÇÃO "+String.format(Locale.ROOT,"%02d",a.completed+1),l+17,t+24,12,MainActivity.MINT,true);String title=a.mission.title;if(title.length()>32)title=title.substring(0,31)+"…";txt(c,title,l+17,t+53,21,MainActivity.TEXT,true);txt(c,Physics.NAMES[a.mission.type]+"  ·  "+Math.round(a.world.distance())+" m",l+17,t+79,15,MainActivity.MUTED,false);rect(c,l+17,t+95,315,3,0xff35505b,2);rect(c,l+17,t+95,315*Math.min(1,(a.completed%26)/26f),3,MainActivity.MINT,2);
  btn(c,"journal","Caderno",r-270,t,94,42,false);btn(c,"gemma",a.director.busy?"Criando…":"Gemma",r-166,t,94,42,false);btn(c,"menu","☰",r-62,t,62,42,false);
  txt(c,a.director.busy?"IA LOCAL · GERANDO MISTÉRIO":a.mission.source.toUpperCase(Locale.ROOT),r-266,t+67,11,MainActivity.TEXT,true);
  // Compass: points to the current experiment in camera coordinates.
  double angle=Math.atan2(Physics.stationX(a.completed)-a.world.px,-(Physics.stationZ(a.completed)-a.world.pz))-a.world.yaw;float center=w/2;float arrow=(float)Math.max(-100,Math.min(100,Math.sin(angle)*100));rect(c,center-116,t+9,232,31,0x90102a36,12);txt(c,"N",center-5,t+30,12,MainActivity.MUTED,true);p.setColor(MainActivity.MINT);Path tri=new Path();tri.moveTo(center+arrow,t+17);tri.lineTo(center+arrow-5,t+27);tri.lineTo(center+arrow+5,t+27);tri.close();c.drawPath(tri,p);
  p.setColor(0xccedf8ef);p.setStrokeWidth(1.5f);c.drawLine(w/2-7,h/2,w/2+7,h/2,p);c.drawLine(w/2,h/2-7,w/2,h/2+7,p);
  float jx=l+79,jy=b-79;p.setColor(0x55122b36);c.drawCircle(jx,jy,66,p);p.setStyle(Paint.Style.STROKE);p.setColor(0x8873c9bb);p.setStrokeWidth(2);c.drawCircle(jx,jy,66,p);p.setStyle(Paint.Style.FILL);p.setColor(0xaa84d4c3);c.drawCircle(jx+sx*42,jy+sy*42,26,p);txt(c,"MOVER",jx-24,b+1,11,MainActivity.TEXT,true);
  btn(c,"jump","↑",r-64,b-127,64,60,false);btn(c,"remove","−",r-140,b-56,62,54,false);btn(c,"place","+",r-66,b-56,62,54,false);
  boolean near=a.world.distance()<=6;btn(c,"investigate",near?"INVESTIGAR RUÍNA":"SIGA A LUZ",w/2-126,b-70,252,54,near);txt(c,"Arraste à direita para olhar",w/2-104,b+7,13,MainActivity.TEXT,false);
  txt(c,a.world.fps+" FPS",r-53,b-148,11,0xaaffffff,false);c.restore();postInvalidateDelayed(33);
 }
 void cancelTouch(){stickId=lookId=-1;sx=sy=0;a.world.moveX=a.world.moveZ=0;}
 @Override public boolean onTouchEvent(android.view.MotionEvent e){float x=e.getX(e.getActionIndex())/scale,y=e.getY(e.getActionIndex())/scale;int id=e.getPointerId(e.getActionIndex()),act=e.getActionMasked();if(act==MotionEvent.ACTION_DOWN||act==MotionEvent.ACTION_POINTER_DOWN){for(Map.Entry<String,RectF> b:buttons.entrySet())if(b.getValue().contains(x,y)){action(b.getKey());return true;}if(a.started){if(x<w*.34&&y>h*.45&&stickId<0){stickId=id;stick(x,y);}else if(lookId<0){lookId=id;lx=x;ly=y;}}}else if(act==MotionEvent.ACTION_MOVE){for(int i=0;i<e.getPointerCount();i++){int pid=e.getPointerId(i);float xx=e.getX(i)/scale,yy=e.getY(i)/scale;if(pid==stickId)stick(xx,yy);if(pid==lookId){a.world.yaw+=(xx-lx)*.004f;a.world.pitch=Math.max(-1.25f,Math.min(1.25f,a.world.pitch-(yy-ly)*.004f));lx=xx;ly=yy;}}}else if(act==MotionEvent.ACTION_UP||act==MotionEvent.ACTION_POINTER_UP){if(id==stickId){stickId=-1;sx=sy=0;a.world.moveX=a.world.moveZ=0;}if(id==lookId)lookId=-1;}else if(act==MotionEvent.ACTION_CANCEL)cancelTouch();return true;}
 private void stick(float x,float y){sx=(x-(l+79))/55;sy=(y-(b-79))/55;float length=(float)Math.hypot(sx,sy);if(length>1){sx/=length;sy/=length;}a.world.moveX=sx;a.world.moveZ=-sy;}
 private void action(String key){switch(key){case "start":a.start();break;case "gemma":a.gemmaMenu();break;case "journal":a.journal();break;case "menu":a.pauseMenu();break;case "jump":a.world.jump=1;break;case "remove":a.world.edit(false);break;case "place":a.world.edit(true);break;case "investigate":a.investigate();break;}}
}
