package com.edward.physicalcraft;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import android.media.ToneGenerator;import android.media.AudioManager;import java.util.*;import org.json.*;

public final class MainActivity extends Activity {
 static final int BG=Color.rgb(12,29,39),PANEL=Color.rgb(23,45,55),MINT=Color.rgb(118,242,206),TEXT=Color.rgb(234,244,241),MUTED=Color.rgb(158,184,187),GOLD=Color.rgb(255,216,144);
 WorldView world;HudView hud;Physics.Mission mission;GemmaDirector director;ModelDownload download;private TextView aiStatus;int completed;long worldSeed=730211;boolean started=false,sound=true,autoGemma=true;String lastMessage="";private ToneGenerator tones;private final Handler handler=new Handler(Looper.getMainLooper());private Dialog active;private boolean resumed;
 @Override public void onCreate(Bundle b){super.onCreate(b);
  String previous=CrashReport.take(this);
  if(previous!=null){showFailure(previous);return;}
  try{initializeGame();}catch(RuntimeException|LinkageError error){startupFailure(error);}
 }
 private void initializeGame(){getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setDecorFitsSystemWindows(false);director=GemmaDirector.get(this);download=ModelDownload.get(this);android.content.SharedPreferences p=getSharedPreferences("expedition",0);completed=p.getInt("completed",0);worldSeed=p.getLong("seed",730211);sound=p.getBoolean("sound",true);autoGemma=p.getBoolean("autoGemma",true);mission=Physics.create(completed,worldSeed);
  try{String saved=p.getString("mission","");if(!saved.isEmpty()){JSONObject j=new JSONObject(saved);mission=Blueprint.parse(saved,completed);mission.source=j.optString("source","Campanha local");}}catch(Exception ignored){}
  world=new WorldView(this);world.missionIndex=completed;world.environment=mission.environment;world.thirdPerson=p.getBoolean("thirdPerson",true);world.cameraDistance=p.getFloat("cameraDistance",6.2f);world.equipment.selected=p.getInt("tool",0);world.equipment.crystals=p.getInt("crystals",0);world.equipment.swordLevel=p.getInt("swordLevel",0);
  try{JSONObject damage=new JSONObject(p.getString("targetDamage","{}"));Iterator<String> keys=damage.keys();while(keys.hasNext()){String key=keys.next();world.equipment.damage.put(key,damage.getInt(key));}}catch(Exception ignored){}
  try{JSONObject edits=new JSONObject(p.getString("edits","{}"));Iterator<String> it=edits.keys();while(it.hasNext()){String k=it.next();world.edits.put(k,edits.getInt(k));}}catch(Exception ignored){}
  world.restore(Double.longBitsToDouble(p.getLong("x",Double.doubleToLongBits(5))),Double.longBitsToDouble(p.getLong("z",Double.doubleToLongBits(8))),p.getFloat("yaw",.87f),p.getFloat("pitch",-.08f));
  FrameLayout root=new FrameLayout(this);root.addView(world);hud=new HudView(this);root.addView(hud);setContentView(root);root.post(this::immersive);root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets safe=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());hud.safeLeft=safe.left;hud.safeRight=safe.right;hud.safeTop=safe.top;hud.safeBottom=safe.bottom;return in;});try{tones=new ToneGenerator(AudioManager.STREAM_MUSIC,35);}catch(Exception ignored){}
 }
 void startupFailure(Throwable error){android.util.Log.e("PhysicalCraft","Startup failed",error);showFailure(CrashReport.describe(error));}
 private void showFailure(String report){
  if(world!=null){world.paused=true;world.onPause();}
  LinearLayout box=panel("PHYSICALCRAFT · DIAGNÓSTICO","Não foi possível abrir o mundo");
  box.addView(text("Copie o diagnóstico e envie na conversa para corrigirmos a falha. Seu progresso continua salvo.",17,TEXT));
  TextView details=text(report,12,MUTED);details.setTextIsSelectable(true);box.addView(details);
  box.addView(button("Copiar diagnóstico",()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("PhysicalCraft",report));message("Diagnóstico copiado.");}));
  box.addView(button("Tentar novamente",()->recreate()));
  ScrollView scroll=new ScrollView(this);scroll.addView(box);setContentView(scroll);
 }
 void immersive(){WindowInsetsController controller=getWindow().getInsetsController();if(controller==null)return;controller.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());controller.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}
 private final Runnable downloadPoll=new Runnable(){public void run(){if(!resumed)return;if(download!=null&&director!=null){download.poll(director,()->runOnUiThread(()->{if(!isDestroyed()&&aiStatus!=null)aiStatus.setText(download.status);}));if(aiStatus!=null)aiStatus.setText(download.status.isEmpty()?(director.ready()?director.modelName()+" · instalada":"Nenhuma IA instalada"):download.status);}handler.postDelayed(this,1000);}};
 void start(){started=true;world.paused=false;hud.invalidate();}
 void save(){if(world==null)return;try{JSONObject edits=new JSONObject();for(Map.Entry<String,Integer> e:world.edits.entrySet())edits.put(e.getKey(),e.getValue());JSONObject damage=new JSONObject();for(Map.Entry<String,Integer> e:world.equipment.damage.entrySet())damage.put(e.getKey(),e.getValue());getSharedPreferences("expedition",0).edit().putBoolean("thirdPerson",world.thirdPerson).putFloat("cameraDistance",world.cameraDistance).putInt("tool",world.equipment.selected).putInt("crystals",world.equipment.crystals).putInt("swordLevel",world.equipment.swordLevel).putString("targetDamage",damage.toString()).putInt("completed",completed).putLong("seed",worldSeed).putLong("x",Double.doubleToLongBits(world.px)).putLong("z",Double.doubleToLongBits(world.pz)).putFloat("yaw",world.yaw).putFloat("pitch",world.pitch).putString("mission",Blueprint.json(mission).toString()).putString("edits",edits.toString()).putBoolean("sound",sound).putBoolean("autoGemma",autoGemma).apply();}catch(Exception ignored){}}
 @Override protected void onResume(){super.onResume();resumed=true;handler.post(downloadPoll);if(world!=null){world.onResume();world.paused=!started||active!=null;}immersive();}
 @Override protected void onPause(){resumed=false;handler.removeCallbacks(downloadPoll);save();if(world!=null){world.paused=true;world.moveX=world.moveZ=0;world.onPause();}super.onPause();}
 @Override protected void onDestroy(){if(world!=null)world.close();if(tones!=null)tones.release();super.onDestroy();}
 @Override public void onBackPressed(){if(active!=null)active.dismiss();else if(world!=null&&hud!=null)pauseMenu();else finish();}
 void play(boolean success){if(sound&&tones!=null)tones.startTone(success?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_BEEP,150);}
 void message(String s){lastMessage=s;Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 int dp(float x){return (int)(getResources().getDisplayMetrics().density*x+.5f);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));return t;}
 Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(BG);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable bg=new GradientDrawable();bg.setColor(MINT);bg.setCornerRadius(dp(14));b.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.topMargin=dp(10);b.setLayoutParams(lp);b.setOnClickListener(v->action.run());return b;}
 LinearLayout panel(String eyebrow,String title){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(24),dp(16),dp(24),dp(20));box.setBackgroundColor(BG);TextView over=text(eyebrow,12,MINT);over.setLetterSpacing(.12f);box.addView(over);TextView h=text(title,26,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);box.addView(h);return box;}
 void show(LinearLayout content){if(active!=null)active.dismiss();world.paused=true;world.moveX=world.moveZ=0;hud.cancelTouch();Dialog d=new Dialog(this);active=d;ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.addView(content);d.setContentView(scroll);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.getWindow().setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(48),dp(790)),getResources().getDisplayMetrics().heightPixels-dp(28));d.setOnDismissListener(x->{if(active==d)active=null;world.paused=!started||!resumed;world.moveX=world.moveZ=0;immersive();});d.show();d.getWindow().setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(48),dp(790)),getResources().getDisplayMetrics().heightPixels-dp(28));}
 void dismiss(){if(active!=null)active.dismiss();}
 void pauseMenu(){LinearLayout p=panel("EXPEDIÇÃO SALVA NO CELULAR","Seu mundo, seu ritmo");p.addView(text("Explore a ilha. Siga a coluna de luz. Toque em INVESTIGAR perto da ruína para abrir um experimento.",17,MUTED));p.addView(button("Continuar explorando",()->{dismiss();start();}));p.addView(button("Voltar à ruína atual",()->{world.camp();dismiss();start();}));p.addView(button("Caderno de descobertas",this::journal));p.addView(button("Mochila · espada, picareta e cristais",this::inventory));p.addView(button(world.thirdPerson?"Câmera: terceira pessoa":"Câmera: primeira pessoa",()->{world.thirdPerson=!world.thirdPerson;save();pauseMenu();}));
  p.addView(text("Distância da câmera",15,MUTED));SeekBar zoom=new SeekBar(this);zoom.setMax(50);zoom.setProgress((int)((world.cameraDistance-3.5f)*10));zoom.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){save();}public void onProgressChanged(SeekBar s,int value,boolean user){world.cameraDistance=3.5f+value/10f;}});p.addView(zoom);
  p.addView(button("IA local · baixar ou configurar",this::gemmaMenu));p.addView(button(sound?"Desligar sons":"Ligar sons",()->{sound=!sound;save();pauseMenu();}));p.addView(text("Mover: círculo esquerdo. Olhar: arraste à direita. ↑ pula. + / − alteram o terreno sob a mira. Alterações ficam salvas.",15,MUTED));show(p);}
 void journal(){LinearLayout p=panel("CADERNO DE CAMPO",completed+" mistérios resolvidos");p.addView(text("Da primeira força à luz quântica. Dois experimentos por capítulo; depois, expedições de revisão continuam.",17,MUTED));for(int i=0;i<Physics.NAMES.length;i++){final int type=i;boolean unlocked=completed>=i*2;TextView t=text((completed>i*2+1?"✓  ":unlocked?"●  ":"○  ")+String.format(Locale.ROOT,"%02d",i+1)+"  "+Physics.NAMES[i],17,unlocked?TEXT:MUTED);p.addView(t);if(unlocked){t.setOnClickListener(v->{LinearLayout q=panel("NOTAS · "+Physics.NAMES[type],Physics.TITLES[type]);q.addView(text(Physics.RULES[type],19,TEXT));q.addView(text("As simulações usam modelos idealizados. As condições do modelo aparecem junto ao experimento.",15,MUTED));q.addView(button("Voltar ao caderno",this::journal));show(q);});}}
  p.addView(button("Voltar ao mundo",this::dismiss));show(p);}
 void investigate(){if(world.distance()>6){message("Siga a luz verde até a ruína ("+Math.round(world.distance())+" m). Use o menu para voltar até ela.");return;}openExperiment();}
 void openExperiment(){Physics.Mission m=mission;LinearLayout p=panel("MISTÉRIO "+(completed+1)+"  /  "+Physics.NAMES[m.type].toUpperCase(Locale.ROOT),m.title);p.addView(text(m.story,17,TEXT));p.addView(text(m.source+" · modelo físico validado pelo jogo",12,MINT));
  ExperimentView visual=new ExperimentView(this,m);p.addView(visual,new LinearLayout.LayoutParams(-1,dp(175)));p.addView(text("OBJETIVO  ·  "+Physics.OUTPUT[m.type]+" = "+Physics.fmt(m.target)+" "+Physics.UNIT[m.type],18,GOLD));p.addView(text(m.context(),14,MUTED));
  TextView input=text("",18,TEXT);p.addView(input);SeekBar slider=new SeekBar(this);slider.setMax(100);slider.setProgress(5);p.addView(slider,new LinearLayout.LayoutParams(-1,dp(40)));TextView result=text("Ajuste o instrumento e faça uma previsão. Depois, execute o experimento.",16,MUTED);p.addView(result);final double[] value={m.min+(m.max-m.min)*.05};input.setText(Physics.INPUT[m.type]+": "+Physics.fmt(value[0]));visual.value=value[0];
  slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int v,boolean user){value[0]=m.min+(m.max-m.min)*v/100.;input.setText(Physics.INPUT[m.type]+": "+Physics.fmt(value[0]));visual.value=value[0];visual.running=false;visual.invalidate();result.setText("Previsão pronta? Execute para medir.");}});
  final boolean[] solvedOnce={false};Button test=button("Executar experimento",()->{if(solvedOnce[0])return;visual.start();double measured=m.value(value[0]);boolean ok=m.success(value[0]);play(ok);result.setText("MEDIDO  "+Physics.fmt(measured)+" "+Physics.UNIT[m.type]+(ok?"  ·  Evidência confirmada!":"  ·  "+(measured<m.target?"Abaixo":"Acima")+" do objetivo. Ajuste e tente novamente."));result.setTextColor(ok?MINT:GOLD);if(ok){solvedOnce[0]=true;final Dialog experimentDialog=active;LinearLayout win=panel("DESCOBERTA CONFIRMADA",m.title);win.addView(text(Physics.RULES[m.type],20,TEXT));win.addView(text("Você mediu "+Physics.fmt(measured)+" "+Physics.UNIT[m.type]+". A tolerância experimental é de aproximadamente 3,5%.",16,MUTED));win.addView(button("Registrar e abrir a próxima ruína",()->advance(m)));handler.postDelayed(()->{if(!isFinishing()&&mission==m&&active==experimentDialog)show(win);},1900);}});p.addView(test);
  p.addView(button("Consultar princípio físico",()->{result.setText(Physics.RULES[m.type]);result.setTextColor(MUTED);}));p.addView(button("Voltar à exploração",this::dismiss));show(p);}
 void advance(Physics.Mission solved){if(mission!=solved)return;completed++;mission=Physics.create(completed,worldSeed+completed*7919L);world.missionIndex=completed;world.environment=mission.environment;world.refreshTerrain();save();dismiss();world.camp();message("Descoberta registrada. Uma nova ruína surgiu adiante.");if(autoGemma&&director.ready()&&!director.busy)generate(false);}
 void generate(boolean showInfo){if(!director.ready()){gemmaMenu();return;}if(director.busy){message("A IA está preparando o próximo mistério.");return;}Physics.Mission base=mission;if(showInfo)dismiss();message("IA criando um mistério no celular. Você pode continuar explorando.");director.generate(base,(generated,error)->runOnUiThread(()->{if(isFinishing()||isDestroyed())return;if(error!=null){message(error);return;}if(mission!=base){message("A geração terminou após sua descoberta; a fase atual foi preservada.");return;}mission=generated;world.environment=mission.environment;world.refreshTerrain();save();if(active!=null)dismiss();message("Novo mistério da IA implantado na ruína. Aproxime-se para investigar.");}));}
 void equip(int item){world.equipment.selected=item;save();}
 void inventory(){LinearLayout p=panel("MOCHILA DO EXPLORADOR",world.equipment.crystals+" cristais coletados");
  p.addView(text("Você começa com uma espada de exploração e uma picareta. Aproxime-se dos sentinelas dourados e use GOLPE. Eles são alvos de treino e não atacam.",17,TEXT));
  p.addView(button("Equipar espada · nível "+(world.equipment.swordLevel+1),()->{equip(Equipment.SWORD);dismiss();}));
  p.addView(button("Equipar picareta · retirar blocos",()->{equip(Equipment.PICKAXE);dismiss();}));
  p.addView(text("Cada sentinela desativado dá 1 cristal. Novas ruínas trazem novos sentinelas.",16,MUTED));
  p.addView(button(world.equipment.swordLevel>=2?"Espada no nível máximo":"Melhorar espada · 3 cristais",()->{if(world.equipment.upgrade()){save();inventory();}else message("Você precisa de 3 cristais; o nível máximo é 3.");}));p.addView(button("Voltar ao mundo",this::dismiss));show(p);
 }
 void gemmaMenu(){LinearLayout p=panel("INTELIGÊNCIA NO SEU CELULAR","IA local");
  aiStatus=text(download.status.isEmpty()?(director.ready()?director.modelName()+" · instalada":"Nenhuma IA instalada"):download.status,19,MINT);p.addView(aiStatus);
  p.addView(text("Baixe uma vez. Depois, a IA cria mistérios sem internet. Suas partidas e seus pedidos não são enviados a servidores.",17,TEXT));
  if(download.active()){p.addView(button("Cancelar download",()->{download.cancel();gemmaMenu();}));}
  else p.addView(button("Baixar IA · Qwen 1.5B · 1,60 GB",()->{if(director.busy){message("Aguarde a IA terminar.");return;}try{download.start();gemmaMenu();}catch(RuntimeException e){message(e.getMessage());}}));
  p.addView(text("Sem cadastro. Reserve 3,4 GB livres para a instalação. O Android continua o download em segundo plano. Use Wi-Fi para evitar gastar seu pacote de dados.",15,MUTED));
  if(director.ready())p.addView(button(director.busy?"IA trabalhando…":"Gerar e implantar mistério",()->generate(true)));
  p.addView(button(autoGemma?"Novos mistérios automáticos: ligados":"Novos mistérios automáticos: desligados",()->{autoGemma=!autoGemma;save();gemmaMenu();}));
  p.addView(text("Prefere Gemma? O provedor exige login e aceite da licença. Baixe gemma3-1b-it-int4.litertlm e importe abaixo. Apenas abrir a página não instala o modelo.",15,MUTED));
  p.addView(button("Gemma 1B · abrir página e autorizar",()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://huggingface.co/litert-community/Gemma3-1B-IT")));}catch(ActivityNotFoundException e){message("Nenhum navegador disponível.");}}));
  p.addView(button("Importar modelo .litertlm já baixado",()->{if(director.busy||download.active()){message("Aguarde ou cancele o download atual.");return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,41);}));
  p.addView(text("A campanha, a espada e a exploração funcionam sem IA. Modelos .gguf e .task não são compatíveis.",14,MUTED));p.addView(button("Voltar ao mundo",this::dismiss));show(p);
 }
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==41&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri uri=data.getData();message("Copiando e validando o modelo. Aguarde; pode levar alguns minutos.");dismiss();director.importModel(uri,error->runOnUiThread(()->{if(isFinishing()||isDestroyed())return;message(error==null?"Modelo importado e inicializado com sucesso.":error);gemmaMenu();}));}}
}
