package com.edward.physicalcraft;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import android.media.ToneGenerator;import android.media.AudioManager;import java.util.*;import org.json.*;

public final class MainActivity extends Activity {
 static final int BG=Color.rgb(12,29,39),PANEL=Color.rgb(23,45,55),MINT=Color.rgb(118,242,206),TEXT=Color.rgb(234,244,241),MUTED=Color.rgb(158,184,187),GOLD=Color.rgb(255,216,144);
 WorldView world;HudView hud;Physics.Mission mission;GemmaDirector director;int completed;long worldSeed=730211;boolean started=false,sound=true,autoGemma=true;String lastMessage="";private ToneGenerator tones;private final Handler handler=new Handler(Looper.getMainLooper());private Dialog active;private boolean resumed;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setDecorFitsSystemWindows(false);immersive();director=new GemmaDirector(this);android.content.SharedPreferences p=getSharedPreferences("expedition",0);completed=p.getInt("completed",0);worldSeed=p.getLong("seed",730211);sound=p.getBoolean("sound",true);autoGemma=p.getBoolean("autoGemma",true);mission=Physics.create(completed,worldSeed);
  try{String saved=p.getString("mission","");if(!saved.isEmpty()){JSONObject j=new JSONObject(saved);mission=Blueprint.parse(saved,completed);mission.source=j.optString("source","Campanha local");}}catch(Exception ignored){}
  world=new WorldView(this);world.missionIndex=completed;world.environment=mission.environment;
  try{JSONObject edits=new JSONObject(p.getString("edits","{}"));Iterator<String> it=edits.keys();while(it.hasNext()){String k=it.next();world.edits.put(k,edits.getInt(k));}}catch(Exception ignored){}
  world.restore(Double.longBitsToDouble(p.getLong("x",Double.doubleToLongBits(5))),Double.longBitsToDouble(p.getLong("z",Double.doubleToLongBits(8))),p.getFloat("yaw",.87f),p.getFloat("pitch",-.08f));
  FrameLayout root=new FrameLayout(this);root.addView(world);hud=new HudView(this);root.addView(hud);setContentView(root);root.post(this::immersive);root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets safe=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());hud.safeLeft=safe.left;hud.safeRight=safe.right;hud.safeTop=safe.top;hud.safeBottom=safe.bottom;return in;});try{tones=new ToneGenerator(AudioManager.STREAM_MUSIC,35);}catch(Exception ignored){}
 }
 void immersive(){WindowInsetsController controller=getWindow().getInsetsController();if(controller==null)return;controller.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());controller.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}
 void start(){started=true;world.paused=false;hud.invalidate();}
 void save(){if(world==null)return;try{JSONObject edits=new JSONObject();for(Map.Entry<String,Integer> e:world.edits.entrySet())edits.put(e.getKey(),e.getValue());getSharedPreferences("expedition",0).edit().putInt("completed",completed).putLong("seed",worldSeed).putLong("x",Double.doubleToLongBits(world.px)).putLong("z",Double.doubleToLongBits(world.pz)).putFloat("yaw",world.yaw).putFloat("pitch",world.pitch).putString("mission",Blueprint.json(mission).toString()).putString("edits",edits.toString()).putBoolean("sound",sound).putBoolean("autoGemma",autoGemma).apply();}catch(Exception ignored){}}
 @Override protected void onResume(){super.onResume();resumed=true;if(world!=null){world.onResume();world.paused=!started||active!=null;}immersive();}
 @Override protected void onPause(){resumed=false;save();if(world!=null){world.paused=true;world.moveX=world.moveZ=0;world.onPause();}super.onPause();}
 @Override protected void onDestroy(){if(world!=null)world.close();if(director!=null)director.close();if(tones!=null)tones.release();super.onDestroy();}
 @Override public void onBackPressed(){if(active!=null)active.dismiss();else pauseMenu();}
 void play(boolean success){if(sound&&tones!=null)tones.startTone(success?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_BEEP,150);}
 void message(String s){lastMessage=s;Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 int dp(float x){return (int)(getResources().getDisplayMetrics().density*x+.5f);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));return t;}
 Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(BG);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable bg=new GradientDrawable();bg.setColor(MINT);bg.setCornerRadius(dp(14));b.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.topMargin=dp(10);b.setLayoutParams(lp);b.setOnClickListener(v->action.run());return b;}
 LinearLayout panel(String eyebrow,String title){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(24),dp(16),dp(24),dp(20));box.setBackgroundColor(BG);TextView over=text(eyebrow,12,MINT);over.setLetterSpacing(.12f);box.addView(over);TextView h=text(title,26,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);box.addView(h);return box;}
 void show(LinearLayout content){if(active!=null)active.dismiss();world.paused=true;world.moveX=world.moveZ=0;hud.cancelTouch();Dialog d=new Dialog(this);active=d;ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.addView(content);d.setContentView(scroll);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.getWindow().setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(48),dp(790)),getResources().getDisplayMetrics().heightPixels-dp(28));d.setOnDismissListener(x->{if(active==d)active=null;world.paused=!started||!resumed;world.moveX=world.moveZ=0;immersive();});d.show();d.getWindow().setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(48),dp(790)),getResources().getDisplayMetrics().heightPixels-dp(28));}
 void dismiss(){if(active!=null)active.dismiss();}
 void pauseMenu(){LinearLayout p=panel("EXPEDIÇÃO SALVA NO CELULAR","Seu mundo, seu ritmo");p.addView(text("Explore a ilha. Siga a coluna de luz. Toque em INVESTIGAR perto da ruína para abrir um experimento.",17,MUTED));p.addView(button("Continuar explorando",()->{dismiss();start();}));p.addView(button("Voltar à ruína atual",()->{world.camp();dismiss();start();}));p.addView(button("Caderno de descobertas",this::journal));p.addView(button("Gemma · IA local",this::gemmaMenu));p.addView(button(sound?"Desligar sons":"Ligar sons",()->{sound=!sound;save();pauseMenu();}));p.addView(text("Mover: círculo esquerdo. Olhar: arraste à direita. ↑ pula. + / − alteram o terreno sob a mira. Alterações ficam salvas.",15,MUTED));show(p);}
 void journal(){LinearLayout p=panel("CADERNO DE CAMPO",completed+" mistérios resolvidos");p.addView(text("Da primeira força à luz quântica. Dois experimentos por capítulo; depois, expedições de revisão continuam.",17,MUTED));for(int i=0;i<Physics.NAMES.length;i++){final int type=i;boolean unlocked=completed>=i*2;TextView t=text((completed>i*2+1?"✓  ":unlocked?"●  ":"○  ")+String.format(Locale.ROOT,"%02d",i+1)+"  "+Physics.NAMES[i],17,unlocked?TEXT:MUTED);p.addView(t);if(unlocked){t.setOnClickListener(v->{LinearLayout q=panel("NOTAS · "+Physics.NAMES[type],Physics.TITLES[type]);q.addView(text(Physics.RULES[type],19,TEXT));q.addView(text("As simulações usam modelos idealizados. As condições do modelo aparecem junto ao experimento.",15,MUTED));q.addView(button("Voltar ao caderno",this::journal));show(q);});}}
  p.addView(button("Voltar ao mundo",this::dismiss));show(p);}
 void investigate(){if(world.distance()>6){message("Siga a luz verde até a ruína ("+Math.round(world.distance())+" m). Use o menu para voltar até ela.");return;}openExperiment();}
 void openExperiment(){Physics.Mission m=mission;LinearLayout p=panel("MISTÉRIO "+(completed+1)+"  /  "+Physics.NAMES[m.type].toUpperCase(Locale.ROOT),m.title);p.addView(text(m.story,17,TEXT));p.addView(text(m.source+" · modelo físico validado pelo jogo",12,MINT));
  ExperimentView visual=new ExperimentView(this,m);p.addView(visual,new LinearLayout.LayoutParams(-1,dp(175)));p.addView(text("OBJETIVO  ·  "+Physics.OUTPUT[m.type]+" = "+Physics.fmt(m.target)+" "+Physics.UNIT[m.type],18,GOLD));p.addView(text(m.context(),14,MUTED));
  TextView input=text("",18,TEXT);p.addView(input);SeekBar slider=new SeekBar(this);slider.setMax(100);slider.setProgress(5);p.addView(slider,new LinearLayout.LayoutParams(-1,dp(40)));TextView result=text("Ajuste o instrumento e faça uma previsão. Depois, execute o experimento.",16,MUTED);p.addView(result);final double[] value={m.min+(m.max-m.min)*.05};input.setText(Physics.INPUT[m.type]+": "+Physics.fmt(value[0]));visual.value=value[0];
  slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int v,boolean user){value[0]=m.min+(m.max-m.min)*v/100.;input.setText(Physics.INPUT[m.type]+": "+Physics.fmt(value[0]));visual.value=value[0];visual.running=false;visual.invalidate();result.setText("Previsão pronta? Execute para medir.");}});
  final boolean[] solvedOnce={false};Button test=button("Executar experimento",()->{if(solvedOnce[0])return;visual.start();double measured=m.value(value[0]);boolean ok=m.success(value[0]);play(ok);result.setText("MEDIDO  "+Physics.fmt(measured)+" "+Physics.UNIT[m.type]+(ok?"  ·  Evidência confirmada!":"  ·  "+(measured<m.target?"Abaixo":"Acima")+" do objetivo. Ajuste e tente novamente."));result.setTextColor(ok?MINT:GOLD);if(ok){solvedOnce[0]=true;final Dialog experimentDialog=active;LinearLayout win=panel("DESCOBERTA CONFIRMADA",m.title);win.addView(text(Physics.RULES[m.type],20,TEXT));win.addView(text("Você mediu "+Physics.fmt(measured)+" "+Physics.UNIT[m.type]+". A tolerância experimental é de aproximadamente 3,5%.",16,MUTED));win.addView(button("Registrar e abrir a próxima ruína",()->advance(m)));handler.postDelayed(()->{if(!isFinishing()&&mission==m&&active==experimentDialog)show(win);},1900);}});p.addView(test);
  p.addView(button("Consultar princípio físico",()->{result.setText(Physics.RULES[m.type]);result.setTextColor(MUTED);}));p.addView(button("Voltar à exploração",this::dismiss));show(p);}
 void advance(Physics.Mission solved){if(mission!=solved)return;completed++;mission=Physics.create(completed,worldSeed+completed*7919L);world.missionIndex=completed;world.environment=mission.environment;save();dismiss();world.camp();message("Descoberta registrada. Uma nova ruína surgiu adiante.");if(autoGemma&&director.ready()&&!director.busy)generate(false);}
 void generate(boolean showInfo){if(!director.ready()){gemmaMenu();return;}if(director.busy){message("O Gemma está preparando o próximo mistério.");return;}Physics.Mission base=mission;if(showInfo)dismiss();message("Gemma criando um mistério no celular. Você pode continuar explorando.");director.generate(base,(generated,error)->runOnUiThread(()->{if(isFinishing()||isDestroyed())return;if(error!=null){message(error);return;}if(mission!=base){message("A geração terminou após sua descoberta; a fase atual foi preservada.");return;}mission=generated;world.environment=mission.environment;world.refreshTerrain();save();if(active!=null)dismiss();message("Novo mistério do Gemma implantado na ruína. Aproxime-se para investigar.");}));}
 void gemmaMenu(){LinearLayout p=panel("DIRETOR DE MISTÉRIOS · NO CELULAR","Gemma local");p.addView(text(director.busy?"Trabalhando no celular…":director.ready()?"Modelo importado · pronto para gerar":"Importe o modelo para criar novos mistérios",20,director.ready()?MINT:GOLD));p.addView(text("O Gemma cria a narrativa, os parâmetros e o ambiente de cada nova fase. O jogo verifica o formato e calcula a solução antes de implantar.",17,TEXT));p.addView(text("1. Abra a página do modelo e aceite a licença Gemma.\n2. Baixe gemma3-1b-it-int4.litertlm (cerca de 584 MB).\n3. Volte e importe o arquivo. A inferência funciona offline.",16,MUTED));p.addView(button("Abrir download oficial do Gemma",()->{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://huggingface.co/litert-community/Gemma3-1B-IT/blob/main/gemma3-1b-it-int4.litertlm")));}));p.addView(button("Importar arquivo .litertlm",()->{if(director.busy){message("Aguarde o Gemma terminar.");return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,41);}));if(director.ready())p.addView(button("Gerar e implantar novo mistério",()->generate(true)));p.addView(button(autoGemma?"Geração automática: ligada":"Geração automática: desligada",()->{autoGemma=!autoGemma;save();gemmaMenu();}));p.addView(text("A campanha funciona sem modelo. Gerações inválidas são rejeitadas, preservando a fase atual. Modelos .task ou .gguf não são compatíveis. Esta versão usa CPU para compatibilidade.",14,MUTED));p.addView(button("Voltar",this::dismiss));show(p);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==41&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri uri=data.getData();message("Copiando e validando o modelo. Aguarde; pode levar alguns minutos.");dismiss();director.importModel(uri,error->runOnUiThread(()->{if(isFinishing()||isDestroyed())return;message(error==null?"Gemma importado e inicializado com sucesso.":error);gemmaMenu();}));}}
}
